- become: yes
  hosts: all
  name: preconfig-server
  tasks:
    - name: Add the user 'admin' and add it to 'sudo'
      user:
        name: admin
        group: sudo

    - name: Add the user 'admin' and add it to 'admin'
      user:
        name: admin
        group: admin

    - name: Add SSH key to 'admin'
      authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt: name=nginx update_cache=yes state=latest

    - name: Install packages
      apt:
        pkg:
          - mcrypt 
          - git 
          - php{{ php_version }} 
          - php{{ php_version }}-cli 
          - php{{ php_version }}-common 
          - php{{ php_version }}-mbstring 
          - php{{ php_version }}-gd 
          - php{{ php_version }}-intl 
          - php{{ php_version }}-xml 
          - php{{ php_version }}-mysql 
          - php{{ php_version }}-zip 
          - php{{ php_version }}-fpm 
          - php{{ php_version }}-bcmath 
          - php{{ php_version }}-curl 
          - php{{ php_version }}-pgsql
          
    - name: Install database
      apt: name=postgresql-12 update_cache=yes state=latest

    - name: Install node
      apt: name=nodejs update_cache=yes state=latest
    
    - name: Install npm
      apt: name=npm update_cache=yes state=latest

    - name: install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer
    
    - name: Configure nginx
      template: src=./../../templates/nginx/nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - restart php-fpm
        - restart nginx
    
    - name: Configure virtualhost
      template: src=./../../templates/php/{{ php_version }}/default.conf dest=/etc/nginx/sites-available/default
      notify:npm run prod
      
        - restart php-fpm
        - restart nginx

    - name: Configure PHP pool
      copy: 
        src: ./../../templates/php/{{ php_version }}/www.conf 
        dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart php-fpm
    
    - name: Define 'admin' as owner of /var/www/html folder
      file: 
        path: /var/www/html 
        state: directory
        recurse: yes
        owner: admin 
        group: admin
  
  
  handlers:
    - name: restart php-fpm
      service: name=php{{ php_version }}-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted